name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: setup-github-release
        run: sed -i -e 's/<\/servers>/<server><id>github<\/id><username>x-access-token<\/username><password>${GITHUB_TOKEN}<\/password><\/server><\/servers>/g' /home/runner/.m2/settings.xml

      - name: setup-gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: echo ${GPG_PRIVATE_KEY} | base64 --decode | gpg --batch --import

      - name: checkout
        uses: actions/checkout@v1

      - name: caching
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: mvn clean verify deploy -Dgpg.executable=gpg -Dgpg.passphrase=${GPG_PASSPHRASE}

      - name: sonar-analyse
        run: |
          export SONAR_ORGANIZATION=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 1)
          mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io/ \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${GITHUB_REPOSITORY//\//_} \
            -Dsonar.java.binaries=./target/classes
